{"output": "rohan ramchandani, head of European spot trading at citi, was suspended this week and matt gardiner, former chief accountant at barclays and ubs, was suspended this week.", "target": "Rohan Ramchandani, head of European spot trading at Citi, went on leave this week, while Matt Gardiner, a former senior currencies trader at Barclays and UBS, was suspended by Standard Chartered this week."}
{"output": "Especially in cloud computing, there is a big change because European business leaders are now more aware that data stored in usa is subject to the law there and therefore potentially vulnerable...", "target": "A big shift is occurring in cloud computing where European executives have become more aware that data stored in the US is subject to that jurisdiction and therefore potentially vulnerable."}
{"output": "Contributions of gran canaria it is not far to africa.\u201d", "target": "Africa is not at all that far from Gran Canaria."}
{"output": "It has become clear to me that I acted wrongly...", "target": "I've realised my wrongdoing."}
{"output": "dr. georges bwelle is among the top 10 \" cnn heroes of 2013 \".", "target": "Dr. Georges Bwelle is one of the top 10 CNN Heroes of 2013."}
{"output": "Using a high level of technology, it is also possible to obscure the metadata of an e-mail communication, so that it is not even easy to recognize who communicated with whom.", "target": "With great technical effort, it is also possible to conceal the metadata of email communication so that it is not even possible to tell who is communicating with whom."}
{"output": "Together with 32 other people, they were later arrested after the police found heroin and kokain worth 1.5 million pounds and 200.000 pounds in cash in a series of house searches.", "target": "They and 32 other men were later jailed after police seized heroin and cocaine worth \u00a31.5million along with more than \u00a3200,000 in cash during a series of raids."}
{"output": "thermometer still shows 25 degrees..", "target": "When conductor, Bianca Willmann, raised the baton at 7:30 p.m., the thermometer was still reading 25 degrees."}
{"output": "only as a torhuter roman weidenfeller as the first bvb player entered the platter, a short jubilation came up..", "target": "Only when goalkeeper, Roman Weidenfeller, was the first BVB player to step onto the field, did cheers briefly erupt, as is usually the case."}
{"output": "Kristin Kristin Kristin, who warned the drug-boss against police investigation, has to get involved.", "target": "Cocaine-addict lawyer who tipped off Mr Big about police investigation is jailed"}
{"output": "Er estimated in a report dated december 2011 that the handgepackgebuhr spirit annually brings in 50 million us - dollars...", "target": "He estimated in a December 2011 report that Spirit's carry-on fee brings in $50 million a year."}
{"output": "Especially in pfullendorf the water supply will be more expensive.", "target": "Electricity to become more expensive in Pfullendorf"}
{"output": "\u201cThey were called a psychiatric emergency at the mid-twentieth century,\u201d said drescher.\u201d", "target": "\"Back in the middle of the 20th century, it was called a 'psychiatric emergency,'\" said Drescher."}
{"output": "Palm palmer also criticized the use of pencils when marking the voting sheet.'", "target": "Mr Palmer also criticised the use of pencils to mark ballots."}
{"output": "The prosecutor, called \"bash \" by criminals, was arrested in his home in 2011 after the police questioned scarborough, whom he had represented in a tedious drug trial...", "target": "The solicitor, who was nicknamed \"Bash\" and hailed by criminals as a \"top brief,\" was arrested at his home in 2011 following a police surveillance operation into Scarborough, who he had represented in a previous narcotics trial."}
{"output": "I guess Scotland could do quite well in a looser European union if we keep our own sight...", "target": "I suspect that Scotland could do well inside a looser European arrangement provided we kept our own currency."}
{"output": "Steinberg began as a stand-up comedian, but has developed into a respected television and film director as well as an unofficial comedy historian.", "target": "Steinberg started as a standup comedian but has become an accomplished television and film director, as well as an unofficial comedy historian."}
{"output": "It is because of this that \u201cno further inspectorate activities are currently planned.\u201d", "target": "It added that, \"no further inspection activities are currently planned.\""}
{"output": "The secret of the ham is the herb mix with salt..", "target": "The secret of the ham is the mix of herbs combined with salt."}
{"output": "Suppose, however, that it was the first time that kokain was found in such a tunnel construction..", "target": "However, this was the first time that cocaine was found in such a tunnel construction."}
{"output": "The last station of the circuit is the pratorium, and here the participants descend back into the depths.", "target": "The next stop on the tour is the praetorium, where participants once again descend to the depths."}
{"output": "\u201cTo think about big brother and such dinges were a big problem,\u201d explains alauddin khan, head of strategy and result management in nevada\u2019s transport ministry.\u201d", "target": "\"Concerns about Big Brother and those sorts of things were a major problem,\" said Alauddin Khan, who directs strategic and performance management at the Nevada Department of Transportation."}
{"output": "Every manufacturer is planning differently...", "target": "Every manufacturer schedules it in a different way."}
{"output": "Amke gellert - helpenstein'", "target": "Anke Gellert-Helpenstein"}
{"output": "josef winkler has been writing the note of his childishness and youth of the soul for more than 30 years...", "target": "For more than 30 years, Josef Winkler has been writing from the heart, telling of the hardships of his childhood and youth."}
{"output": "A one-time charge or additional one-time fee could be imposed on drivers of hybrid vehicles or other vehicles that use little petrol, so that they would pay a fair fee as well.\u201d", "target": "An extra one-time or annual levy could be imposed on drivers of hybrids and others whose vehicles don't use much gas, so they pay their fair share."}
{"output": "samsung, huawei and htc produce handys that work with google's android operating system, which competes sharply with apple's and microsoft's mobile products.", "target": "Samsung, Huawei and HTC all manufacture phones that operate on Google's Android operating system, which competes fiercely with Apple and Microsoft mobile products."}
{"output": "Section of the accused regretted his conduct yesterday.'", "target": "Yesterday the accused expressed regret for his behaviour."}
{"output": "assad's troops have been fighting in safira against the rebels for weeks, many of whom have ties to al-Qaeda groups...", "target": "Assad's troops have been battling rebels, many of them linked to al-Qaida groups, in Safira for weeks."}
{"output": "fur die Kinder gab es ein kleine Nebenprogramm - \" oma hanne \" alias hannelore stollsteimer ran ein Kasperlheater und read ein paar Geschichten vor, die die Kinder den mittags ubergest\u00f1gt.\u201c.", "target": "For children, there was a small auxiliary programme - \"Oma Hanne\" (Grandma Hanne), a.k.a Hannelore Stollsteimer, performed a 'Kasperl' theater (similar to Punch and Judy) and read some stories, which kept the children entertained throughout the afternoon."}
{"output": "\u201cIt is very important for the national security interests of usa to keep European citizens on board in anticipation of our joint efforts against terrorism,\u201d said murphy, a democrat who is sitting for the first time in the senat and chair of the senator subcommittee on ready-to-see relations and European opportunities, in an interview in washington.\u201d", "target": "\"It's really important for U.S. national security interests for Europeans to stay on board with us with respect to our mutual anti-terrorism endeavors,\" Murphy, a first-term Democrat and chairman of the Senate Foreign Relations Subcommittee on European Affairs, said in an interview from Washington."}
{"output": "In 2004, a complaint was filed by four manners, which appealed to all minority groups, which developed into a collective action.'", "target": "A lawsuit was filed in 2004 by four men, all minorities, and became a class action case."}
