{"output": "Rohan Ramchandani, Citi\u2019s European Spot Trading Manager, has been suspended this week, and Matt Gardiner, former Barclays and UBS senior currency broker, has been suspended this week at Standard Chartered.", "target": "Rohan Ramchandani, head of European spot trading at Citi, went on leave this week, while Matt Gardiner, a former senior currencies trader at Barclays and UBS, was suspended by Standard Chartered this week."}
{"output": "A big change is taking place in cloud computing, because European business leaders are now more aware that data stored in the US is subject to US jurisdiction and therefore potentially vulnerable.", "target": "A big shift is occurring in cloud computing where European executives have become more aware that data stored in the US is subject to that jurisdiction and therefore potentially vulnerable."}
{"output": "Gran Canaria is not far from Africa.", "target": "Africa is not at all that far from Gran Canaria."}
{"output": "I realise that I acted wrongly.", "target": "I've realised my wrongdoing."}
{"output": "Dr. Georges Bwelle is one of the top 10 \"CNN Heroes of 2013\".", "target": "Dr. Georges Bwelle is one of the top 10 CNN Heroes of 2013."}
{"output": "It is also possible to disguise the metadata of an e-mail communication, so that it is not even easy to recognize who communicated with whom.", "target": "With great technical effort, it is also possible to conceal the metadata of email communication so that it is not even possible to tell who is communicating with whom."}
{"output": "Together with 32 others, they were later arrested after police found heroin and cocaine worth \u00a31.5 million and \u00a3200,000 in cash in a series of house searches.", "target": "They and 32 other men were later jailed after police seized heroin and cocaine worth \u00a31.5million along with more than \u00a3200,000 in cash during a series of raids."}
{"output": "When the conductor Bianca Willmann lifts the clock pole at 7.30 p.m., the thermometer still shows 25 degrees.", "target": "When conductor, Bianca Willmann, raised the baton at 7:30 p.m., the thermometer was still reading 25 degrees."}
{"output": "Only when goalkeeper Roman Weidenfeller entered the field as the first BVB player, as always, did a short-lived jubilation.", "target": "Only when goalkeeper, Roman Weidenfeller, was the first BVB player to step onto the field, did cheers briefly erupt, as is usually the case."}
{"output": "A cocaine-dependent lawyer who warned drug lord against police investigation is jailed.", "target": "Cocaine-addict lawyer who tipped off Mr Big about police investigation is jailed"}
{"output": "He estimated in a December 2011 report that Spirit's hand baggage fee brings in $50 million annually.", "target": "He estimated in a December 2011 report that Spirit's carry-on fee brings in $50 million a year."}
{"output": "In Pfullendorf, electricity costs more.", "target": "Electricity to become more expensive in Pfullendorf"}
{"output": "\u201cIn the middle of the twentieth century, this was called a \u201cpsychiatric emergency,\u201d Drescher said.", "target": "\"Back in the middle of the 20th century, it was called a 'psychiatric emergency,'\" said Drescher."}
{"output": "Palmer also criticized the use of pencils to mark ballot papers.", "target": "Mr Palmer also criticised the use of pencils to mark ballots."}
{"output": "The attorney nicknamed \u201cBash\u201d by criminals was arrested at his home in 2011 after police surveillance of Scarborough, whom he represented in a previous drug trial.", "target": "The solicitor, who was nicknamed \"Bash\" and hailed by criminals as a \"top brief,\" was arrested at his home in 2011 following a police surveillance operation into Scarborough, who he had represented in a previous narcotics trial."}
{"output": "I suspect that Scotland could do very well in a looser European union if we keep our own currency.", "target": "I suspect that Scotland could do well inside a looser European arrangement provided we kept our own currency."}
{"output": "Steinberg began as a stand-up comedian, but has developed into a respected television and film director as well as an unofficial comedy historian.", "target": "Steinberg started as a standup comedian but has become an accomplished television and film director, as well as an unofficial comedy historian."}
{"output": "\u201cNo further inspection activities are currently planned.\u201d", "target": "It added that, \"no further inspection activities are currently planned.\""}
{"output": "The secret of the ham is the mixture of spices and salt.", "target": "The secret of the ham is the mix of herbs combined with salt."}
{"output": "However, this is the first time that cocaine has been found in a tunnel of this kind.", "target": "However, this was the first time that cocaine was found in such a tunnel construction."}
{"output": "The next stop of the tour is the Praetorium, where the participants descend again into the depths.", "target": "The next stop on the tour is the praetorium, where participants once again descend to the depths."}
{"output": "\u201cRights against Big Brother and such things were a big problem,\u201d explains Alauddin Khan, Head of Strategy and Results Management at the Nevada Department of Transportation.", "target": "\"Concerns about Big Brother and those sorts of things were a major problem,\" said Alauddin Khan, who directs strategic and performance management at the Nevada Department of Transportation."}
{"output": "Each manufacturer plans differently.", "target": "Every manufacturer schedules it in a different way."}
{"output": "Anke Gellert-Helpenstein", "target": "Anke Gellert-Helpenstein"}
{"output": "For more than 30 years, Josef Winkler has been writing the hardships of his childhood and youth.", "target": "For more than 30 years, Josef Winkler has been writing from the heart, telling of the hardships of his childhood and youth."}
{"output": "An additional one-off fee or annual levy could be imposed on drivers of hybrid vehicles or other low-fuel vehicles so that they, too, pay a fair share.", "target": "An extra one-time or annual levy could be imposed on drivers of hybrids and others whose vehicles don't use much gas, so they pay their fair share."}
{"output": "Samsung, Huawei and HTC make mobile phones that use Google\u2019s Android operating system, which competes fiercely with Apple and Microsoft mobile products.", "target": "Samsung, Huawei and HTC all manufacture phones that operate on Google's Android operating system, which competes fiercely with Apple and Microsoft mobile products."}
{"output": "The defendant regretted his behaviour yesterday.", "target": "Yesterday the accused expressed regret for his behaviour."}
{"output": "Assad\u2019s troops have been fighting the rebels in Safira for weeks, many of whom have links to al-Qaeda groups.", "target": "Assad's troops have been battling rebels, many of them linked to al-Qaida groups, in Safira for weeks."}
{"output": "For the children there was a small program - \"Oma Hanne\" alias Hannelore Stollsteimer performed a puppet show and read some stories, which the children were busy at midday.", "target": "For children, there was a small auxiliary programme - \"Oma Hanne\" (Grandma Hanne), a.k.a Hannelore Stollsteimer, performed a 'Kasperl' theater (similar to Punch and Judy) and read some stories, which kept the children entertained throughout the afternoon."}
{"output": "\u201cIt is very important for the national security interests of the US that Europeans stay on board in our joint efforts against terrorism,\u201d Murphy, a Democrat for the first time in the Senate and Chairman of the Senate Subcommittee on Foreign Relations and European Affairs, said in an interview in Washington.", "target": "\"It's really important for U.S. national security interests for Europeans to stay on board with us with respect to our mutual anti-terrorism endeavors,\" Murphy, a first-term Democrat and chairman of the Senate Foreign Relations Subcommittee on European Affairs, said in an interview from Washington."}
{"output": "In 2004, four men, all of whom belonged to minorities, filed suit, which became a class action.", "target": "A lawsuit was filed in 2004 by four men, all minorities, and became a class action case."}